### ISSUE TITLE
error: implicit declaration of function 'utime', 'kill'

### ISSUE THREAD

**Issue by ryandesign** [kholtman/afio#17]
afio 2.5.2 fails to build on macOS 10.15.7 with clang from Xcode 12.4:

```
afio.c:1208:10: error: implicit declaration of function 'utime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    VOID utime (DirP_curr->d_name, tstamp);
         ^
afio.c:1325:9: error: implicit declaration of function 'utime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          VOID utime (name, tstamp);
               ^
afio.c:1695:6: error: implicit declaration of function 'kill' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            kill(comppid, SIGTERM);
            ^
afio.c:1851:12: error: implicit declaration of function 'utime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      VOID utime (name, tstamp);
           ^
afio.c:3915:11: error: implicit declaration of function 'utime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            VOID utime (fsname, tstamp);
                 ^
afio.c:4429:12: error: implicit declaration of function 'utime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      VOID utime (to, tstamp);
           ^
```

As of Xcode 12, implicit declaration of function is an error. You must provide a function declaration before you call a function.

On standards-compliant modern systems `utime` and `kill` are declared in `<utime.h>` and `<signal.h>` respectively so the solution is to include those headers. I'm not providing a pull request to do so because I suspect you want this code to continue to be buildable by old compilers that are not standards-compliant. The code already includes `<utime.h>` and `<signal.h>` but only in certain conditions (such as on sun or linux systems) that do not take effect on macOS. I'm not familiar enough with your code to know how you would like it to be restructured so that these headers are included on all of the systems where they're needed.

**Comment by kholtman** [comment]
Thanks for your issue reports and pull requests!

On the restructuring to include the headers:  most of the code was written in the 1980s and 1990s, and it still preserves the style used then.   In that style, the way to add the includes needed for macOS would be to insert some lines

#ifdef macOS  (or whatever the capitalisation in the correct identifier is)
#include ...
#include ...
#endif 

among the ifdefs already at the start of afio.c.    You may also have to tweak some of the other .c files in the same way, but as these were written in the 1990s, not the 1980s, they might already be c99 and xcode compliant out of the box.   

To avoid confusion: the afio project is now in a 'maintenance only' mode (see the README file) so it may be several years before I process and close your comments and pull requests by incorporating them into the main code base.

**Comment by ryandesign** [comment]
`#ifdef __APPLE__` is probably sufficient these days to detect all of Apple's current Darwin's-based operating systems (macOS, iOS, iPadOS, tvOS, watchOS). But as I said, I don't expect the issue to be specific to Apple operating systems. I would guess that all modern standards-compliant UNIX operating systems would want these headers to be included for these functions.
